---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapps
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: javawebapps
    spec:
      containers:
      - image: dockerhandson/spring-boot-mongo
        name: javawebapps
        ports:
        - name: javawebapps
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapps
  name: javawebapps
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapps
